package com.denemestaj.stajproje1;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.amqp.rabbit.core.RabbitTemplate;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

@SpringBootApplication
public class StajProje1Application {

    public static void main(String[] args) {
        SpringApplication.run(StajProje1Application.class, args);
    }

    @Bean
    public CommandLineRunner sendMessage(RabbitTemplate rabbitTemplate) {
        return args -> {
            String orijinalMesaj = "PFNQSD4EODYyOTUwMDIxNDMwNDYwMDUwMDgyNjUdAgHFBQAAASQKJQEyNS0wNi0yNjsxMTowNDo0MDMxAAAAAJ4BADxSUD4CPFJQPgI8UlA+L01TWTU8MT5DNTAwLktNWS4yNTU2DQoNCjAuMC4wKDgwMDIzNzIyKQ0KMC45LjEoMTE6MDc6NTcpDQowLjkuMigyNS0wNi0yNikNCjEuOC4wKDAxOTQxNC4wMDQqS1dIKQ0KMS44LjEoMDA3NzMyLjA2NipLV0gpDQoxLjguMigwMDUwMzcuNTg3KktXSCkNCjEuOC4zKDAwNjY0NC4zNTEqS1dIKQ0KMS44LjAqMSgwMTkxNDcuNzM4KktXSCkNCjEuOC4xKjEoMDA3NjE1LjIyNSpLV0gpDQoxLjguMioxKDAwNDk3NS43ODUqS1dIKQ0KMS44LjMqMSgwMDY1NTYuNzI4KktXSCkNCjEuNi4wKDAwMS4xODAqS1cpKDI1LTA2LTIxLDE3OjMwKQ0KMS42LjAqMSgwMDEuMDk2KktXKSgyNS0wNS0yMCwxMzozMCkNCjUuOC4wKDAxMDE2My45OTMqS1ZBUkgpDQo4LjguMCgwMDAwMjMuMjMyKktWQVJIKQ0KNS44LjAqMSgwMDk5OTkuMjk3KktWQVJIKQ0KOC44LjAqMSgwMDAwMjMuMjAwKktWQVJIKQ0KOS43LjAoMDAwLjE5MypLVkEpDQo5Ni43MCgwMC0wMC0wMCwwMDowMCkNCjk2LjcxKDAwLTAwLTAwLDAwOjAwKSgwMCkNCjk2Ljc3LjEqMSgyMy0wNy0yOCwwMDo1MCwyMy0wNy0yOCwwMToxMikNCjk2Ljc3LjIqMSgxOC0wOC0xNSwwOToxMywxOC0wOC0xNSwwOToxNSkNCjk2Ljc3LjMqMSgwMC0wMC0wMCwwMDowMCwwMC0wMC0wMCwwMDowMCkNCjk2LjcuMCg4MCkNCjk2Ljc3LjAqMSgyNS0wNi0xNiwxMzozMywyNS0wNi0xNiwxMzozNikNCjk2Ljc3LjAqMigyNS0wNi0wNCwxNzoyNywyNS0wNi0wNCwxNzozMCkNCjk2Ljc3LjAqMygyNS0wNS0xMSwwNzoyOCwyNS0wNS0xMSwwNzozMykNCjk2Ljc3LjAqNCgyNS0wNC0yMSwwMzo1OCwyNS0wNC0yMSwwNDo0NykNCjMxLjcuMCgwMC40MjYqQSkNCjUxLjcuMCgwMC4zMDkqQSkNCjcxLjcuMCgwMC4wNzIqQSkNCjMyLjcuMCgyNDAuNjgqVikNCjUyLjcuMCgyNDMuMTQqVikNCjcyLjcuMCgyNDIuNDUqVikNCjI5LjcuMCgwMDAuMTAyKktWQSkNCjQ5LjcuMCgwMDAuMDc0KktWQSkNCjY5LjcuMCgwMDAuMDE3KktWQSkNCjMzLjcuMChSSSAwLjc4OCkNCjUzLjcuMChSSSAwLjc2NykNCjczLjcuMChSQyAwLjk5OSkNCjMxLjcuMyglMDAzLjUyKQ0KMzEuNy41KCUwMDAuOTIpDQozMS43LjcoJTAwMS4yOSkNCjMxLjcuOSglMDAwLjU1KQ0KNTEuNy4zKCUwMDUuMTkpDQo1MS43LjUoJTAwMi40NSkNCjUxLjcuNyglMDAyLjczKQ0KNTEuNy45KCUwMDAuNTQpDQo3MS43LjMoJTAwOS42MykNCjcxLjcuNSglMDAzLjYxKQ0KNzEuNy43KCUwMTIuMDQpDQo3MS43LjkoJTAwOS42MykNCjMyLjcuMyglMDAwLjA2KQ0KMzIuNy41KCUwMDAuOTMpDQozMi43LjcoJTAwMC4zOSkNCjMyLjcuOSglMDAwLjA0KQ0KNTIuNy4zKCUwMDAuMTIpDQo1Mi43LjUoJTAwMC43NSkNCjUyLjcuNyglMDAwLjQ2KQ0KNTIuNy45KCUwMDAuMDEpDQo3Mi43LjMoJTAwMC4xNSkNCjcyLjcuNSglMDAwLjg1KQ0KNzIuNy43KCUwMDAuNDIpDQo3Mi43LjkoJTAwMC4wMikNCjk2LjkzKDApTTxFTkQ+"; // buraya normal (Base64 olmayan) hali gelecekse
            //String base64Mesaj = Base64.getEncoder().encodeToString(orijinalMesaj.getBytes(StandardCharsets.UTF_8));


            rabbitTemplate.convertAndSend("enerji-exchange", "enerji-key", orijinalMesaj);
            System.out.println(" base64 mesaj RabbitMQ kuyruğuna gönderildi.");
        };
    }

}
